# Generated by Django 5.2.1 on 2025-06-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='loginpage.listing'),
            preserve_default=False,
        ),
    ]
