# Generated by Django 5.2.1 on 2025-06-11 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_message_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
