# Generated by Django 5.2.1 on 2025-06-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0005_message_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='listing',
        ),
    ]
