# Generated by Django 5.2.1 on 2025-06-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0006_remove_message_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='loginpage.listing'),
            preserve_default=False,
        ),
    ]
